import { access, copyFile, cp, mkdir, readdir, rm, writeFile } from 'node:fs/promises';
import { constants } from 'node:fs';
import path from 'node:path';

const root = process.cwd();
const dist = path.join(root, 'dist');
const marker = path.join(dist, '.generated-by-build-static');

const rootFiles = [
  'robots.txt',
  'sitemap.xml',
  'vercel.json',
];

const assetDirs = [
  'api',
  'css',
  'js',
  'logos',
  'partners',
];

async function exists(filePath) {
  try {
    await access(filePath, constants.F_OK);
    return true;
  } catch {
    return false;
  }
}

async function prepareDist() {
  if (await exists(dist)) {
    if (!await exists(marker)) {
      throw new Error('Refusing to overwrite existing dist/ without .generated-by-build-static marker.');
    }

    await rm(dist, { recursive: true, force: true });
  }

  await mkdir(dist, { recursive: true });
}

async function copyIfPresent(source, destination) {
  if (!await exists(source)) return;
  await copyFile(source, destination);
}

await prepareDist();

const entries = await readdir(root, { withFileTypes: true });
const htmlFiles = entries
  .filter((entry) => entry.isFile() && entry.name.endsWith('.html'))
  .map((entry) => entry.name);

for (const file of [...htmlFiles, ...rootFiles]) {
  await copyIfPresent(path.join(root, file), path.join(dist, file));
}

for (const dir of assetDirs) {
  const source = path.join(root, dir);
  if (!await exists(source)) continue;

  await cp(source, path.join(dist, dir), {
    recursive: true,
    force: true,
    filter: (sourcePath) => !sourcePath.includes(`${path.sep}README.md`),
  });
}

await writeFile(marker, 'Generated by npm run build. Safe to delete and regenerate.\n');

console.log('Static site built in dist/.');
